<#
.SYNOPSIS
  Install, refresh, or remove the Windows Task Scheduler equivalent of
  JobFinderOS's macOS launchd master scheduler.
.DESCRIPTION
  Regenerates config/scheduler.yaml (the same schema scheduler_tick.py already
  reads, whichever installer wrote it) and registers one repeating Scheduled
  Task that fires JobFinderOS_task_scheduler_launcher.ps1 -> scheduler_tick.py.
  All due-window logic (daily/weekly/watch) lives in scheduler_tick.py itself;
  this task's only job is to tick it on an interval, the same role launchd's
  StartInterval plays on the Mac install path.
.PARAMETER Uninstall
  Remove the scheduled task instead of installing it. Leaves config/scheduler.yaml alone.
.EXAMPLE
  .\JobFinderOS_install_task_scheduler.ps1
  .\JobFinderOS_install_task_scheduler.ps1 -DailyHour 7 -WeeklyWeekday 1 -WeeklyHour 8 -WatchHour 9 -TimeZone "America/New_York"
  .\JobFinderOS_install_task_scheduler.ps1 -Uninstall
#>
[CmdletBinding()]
param(
    [int]$DailyHour = 7,
    [int]$DailyMinute = 0,
    # scheduler.yaml convention: 0 = Sunday .. 6 = Saturday (matches the macOS
    # installer / scheduler_tick.py's launchd_weekday_to_python, not native
    # PowerShell [DayOfWeek]).
    [int]$WeeklyWeekday = 1,
    [int]$WeeklyHour = 8,
    [int]$WeeklyMinute = 0,
    [int]$WatchHour = 9,
    [int]$WatchMinute = 0,
    [int]$IntervalSeconds = 1800,
    [string]$TimeZone = "",
    [switch]$Uninstall
)

$ErrorActionPreference = "Stop"
$TaskName = "JobFinderOS Scheduler"
$Root = Split-Path -Parent $PSScriptRoot

if ($Uninstall) {
    if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
        Write-Host "Removed scheduled task '$TaskName'."
    } else {
        Write-Host "No scheduled task named '$TaskName' found; nothing to remove."
    }
    exit 0
}

New-Item -ItemType Directory -Force -Path (Join-Path $Root "logs") | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $Root "config") | Out-Null

$SchedulerYamlPath = Join-Path $Root "config\scheduler.yaml"
$dailyMinutePadded = $DailyMinute.ToString("00")
$weeklyMinutePadded = $WeeklyMinute.ToString("00")
$watchMinutePadded = $WatchMinute.ToString("00")

$schedulerYamlContent = @"
# JobFinderOS master scheduler - due windows. Regenerated by
# scripts/JobFinderOS_install_task_scheduler.ps1. Edit by hand if you like.
#
# Watch job (invoked each scheduler tick; the guard enforces watch.hour on weekdays):
#   jobfinderos_priority_watch.py -> /jobs-priority-watch

start_interval_seconds: $IntervalSeconds

# IANA timezone for all windows (empty = system local time)
timezone: "$TimeZone"

daily:
  hour: $DailyHour
  minute: $DailyMinute

weekly:
  weekday: $WeeklyWeekday     # 0 = Sunday, 1 = Monday, ... 6 = Saturday (same convention as the macOS installer)
  hour: $WeeklyHour
  minute: $WeeklyMinute

watch:
  hour: $WatchHour
  minute: $WatchMinute
"@

# Set-Content -Encoding utf8 prepends a BOM under legacy powershell.exe (verified
# empirically): a plain .NET write with an explicit no-BOM UTF8Encoding gives the
# same BOM-less file on both that and pwsh.
[System.IO.File]::WriteAllText($SchedulerYamlPath, $schedulerYamlContent, (New-Object System.Text.UTF8Encoding($false)))

$LauncherScript = Join-Path $Root "scripts\JobFinderOS_task_scheduler_launcher.ps1"

$Action = New-ScheduledTaskAction -Execute "powershell.exe" `
    -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$LauncherScript`"" `
    -WorkingDirectory $Root

# Repeats every IntervalSeconds indefinitely, same role as launchd's StartInterval.
# [TimeSpan]::MaxValue overflows Task Scheduler's duration format; a long finite
# span (10 years) is the standard "effectively forever" idiom instead.
$TickTrigger = New-ScheduledTaskTrigger -Once -At (Get-Date) `
    -RepetitionInterval (New-TimeSpan -Seconds $IntervalSeconds) `
    -RepetitionDuration (New-TimeSpan -Days 3650)

# -StartWhenAvailable (below) already runs a missed occurrence as soon as you
# next log on, so a separate AtLogOn trigger would be redundant - and verified
# empirically to cost more than it's worth: registering one under a normal
# (non-admin-token) session fails "Access is denied," while the repeating
# Once trigger alone does not. Skipping it keeps this installer elevation-free.
$Settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -StartWhenAvailable -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Hours 2)

# No explicit -Principal either: verified empirically that passing one (even
# just "this user, LogonType Interactive" - the same scope launchd
# LaunchAgents have on the Mac path) also demands elevation and fails "Access
# is denied" under a normal session. Omitting it lets the task default to the
# current user with an interactive logon, which registers fine without
# elevation and behaves the same way.
Register-ScheduledTask -TaskName $TaskName -Action $Action -Trigger $TickTrigger `
    -Settings $Settings -Force | Out-Null

Write-Host "Installed/refreshed scheduled task '$TaskName': ticks scheduler_tick.py every $IntervalSeconds s, catching up at next logon if one was missed."
Write-Host "Wrote $SchedulerYamlPath (daily ${DailyHour}:${dailyMinutePadded}, weekly weekday $WeeklyWeekday at ${WeeklyHour}:${weeklyMinutePadded}, watch ${WatchHour}:${watchMinutePadded})."
Write-Host "Logs: $Root\logs\task-scheduler.log (this task's own output), $Root\logs\launchd-runs.log (scheduler_tick.py's run history - same file the Mac path writes)."
Write-Host "Test now:  Start-ScheduledTask -TaskName '$TaskName'"
Write-Host "Refresh:   re-run this script; Register-ScheduledTask -Force overwrites the existing task"
Write-Host "Uninstall: .\JobFinderOS_install_task_scheduler.ps1 -Uninstall"
